# Generated by Django 3.2 on 2025-11-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drf_authentify.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("header", "Header"), ("cookie", "Cookie")],
                        max_length=12,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[drf_authentify.validators.validate_context],
                    ),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("refresh_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Token",
                "verbose_name_plural": "Authentication Tokens",
                "ordering": ["-created_at"],
                "abstract": False,
                "swappable": "drf_authentify.AuthToken",
            },
        ),
    ]
