# Generated by Django 4.2 on 2025-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_authentify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='token',
            new_name='access_token_hash',
        ),
        migrations.RenameField(
            model_name='authtoken',
            old_name='refresh_token',
            new_name='refresh_token_hash',
        ),
    ]
